### ISSUE TITLE
stamp_changelog: stamp_date expects a string yet docs say it’s a boolean.

### ISSUE THREAD

**Issue by donileo** [pajapro/fastlane-plugin-changelog#51] opened 2020-12-16 23:03 UTC
The documentation invoked via: `fastlane action stamp_changelog` gives that the default for `stamp_date` is `true` a boolean. When running the action though it seems the action is expecting a String. Furthermore when building and passing any string `"false"` or `"12.16.2020"` for `stamp_date` the action always chooses to include the action's pre-formatted date.

**Comment by pajapro** [comment] 2020-12-20 09:52
Hi @donileo ,

> When running the action though it seems the action is expecting a String. Furthermore when building and passing any string "false" or "12.16.2020" for stamp_date the action _always chooses to include the action's pre-formatted date_.

this is by design. The `stamp_date` param is boolean and should enable the user to say whether he/she wants to stamp current date, which as you said is in [specific format](https://github.com/pajapro/fastlane-plugin-changelog/blob/master/lib/fastlane/plugin/changelog/actions/update_changelog.rb#L52).

I will close this issue as I see that you already created another one + PR

**Closed by pajapro** 2020-12-20 09:52 UTC
